export const vaccins = [{
  id: '1',
  nom: 'BBIBP-CorV',
  image: 'bbibp-corv.jpg',
  inventeurs: 'Sinopharm',
  lieux_de_production: 'Chine',
  technologie: 'virus inactivé',
  quantite: '420',
  prix_unitaire: '17',
  approuve: 'oui',
},
{
  id: '2',
  nom: 'Sputnik V',
  image: 'sputnik-v.jpg',
  inventeurs: 'Gamaleya',
  lieux_de_production: 'Russie, Inde',
  technologie: 'adenovirus',
  quantite: '130',
  prix_unitaire: '12',
  approuve: 'non',
},
{
  id: '3',
  nom: 'AZD1222',
  image: 'azd1222.jpg',
  inventeurs: 'AstraZeneca, University of Oxford',
  lieux_de_production: 'Royaume Unis, Brésil, Inde',
  technologie: 'adenovirus',
  quantite: '5028',
  prix_unitaire: '1.78',
  approuve: 'non',
},
{
  id: '4',
  nom: 'Tozinameran',
  image: 'tozinameran.jpg',
  inventeurs: 'BioNTech, Pfizer, Fosun Pharma',
  lieux_de_production: 'Allemagne, USA',
  technologie: 'ARN messager',
  quantite: '980',
  prix_unitaire: '14',
  approuve: 'oui',
},
{
  id: '5',
  nom: 'mRNA-1273',
  image: 'mrna-1273.jpg',
  inventeurs: 'Moderna, NIAID, BARDA',
  lieux_de_production: 'USA',
  technologie: 'ARN messager',
  quantite: '240',
  prix_unitaire: '28',
  approuve: 'non',
},
{
  id: '6',
  nom: 'Ad26.COV2.S',
  image: 'ad26-cov2-s.jpg',
  inventeurs: 'Johnson & Johnson, BIDMC',
  lieux_de_production: 'USA, Amérique du Sud, Ukraine, Afrique du Sud',
  technologie: 'adenovirus',
  quantite: '110',
  prix_unitaire: '31',
  approuve: 'non',
}];
